apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: docker.io/thexboarder/nginx@sha256:4c797faf0ed02157650e8ce8dbab25f22bc9060259e3069b9eae3ddf9eda96c6
      ports:
        - containerPort: 80
